import "@/styles/globals.css";

import Head from "next/head";
import type { AppProps } from "next/app";

import { MsalProvider } from "@azure/msal-react";

import { useMsalInstance, useMsalToken } from "@/lib/auth/msal";
import { APP_NAME } from "@/lib/configs/constants";
import { loginRequest } from "@/lib/configs/authConfig";

export default function App(appProps: AppProps) {
    const msalInstance = useMsalInstance();

    return (
        <MsalProvider instance={msalInstance}>
            <AppWithData {...appProps} />
        </MsalProvider>
    );
}

const AppWithData = ({ Component, pageProps }: AppProps) => {
    const token = useMsalToken("userToken", loginRequest);
    // const tokenAPI = useMsalToken("apiToken", apiRequest);
    console.log("Token from app.tsx", token);
    // console.log("API Token from app.tsx", tokenAPI);

    return (
        <>
            <div>
                <Head>
                    <title>{APP_NAME}</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <meta
                        name="viewport"
                        content="width=device-width, initial-scale=1"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Component {...pageProps} />
            </div>
        </>
    );
};
